name: ai_food_ordering
description: "AI-powered food ordering application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Networking
  dio: ^5.6.0
  connectivity_plus: ^6.1.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  
  # AI Integration
  http: ^1.2.2
  
  # UI Components
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  image_picker: ^1.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.4.0
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Code Generation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/